server:
  port: 7073

spring:
  application:
    name: FUNDOO_GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: FUNDOO-USER-SERVICE
          uri:
            lb://FUNDOO-USER-SERVICE
          predicates:
          - Path=/user/**


        - id: FUNDOO-NOTE-SERVICE
          uri:
            lb://FUNDOO-NOTE-SERVICE
          predicates:
          - Path=/notes/**




eureka:
  client:
    service-url:
      defultZone: http://localhost:8761/eureka